---
collections:
  # general
  - name: ansible.utils
    version: 6.0.0
  # ansible controller
  - name: infra.controller_configuration
  # linux
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.1.0
  - name: containers.podman
    version: 1.18.0
  # windows
  - name: chocolatey.chocolatey
  - name: community.windows
  # cloud
  - name: azure.azcollection
  - name: amazon.aws
    version: 10.1.2
...